export const ADD_CONTACT = 'ADD_CONTACT';
export const EDIT_CONTACT = 'EDIT_CONTACT';
export const UPDATE_CONTACT = 'UPDATE_CONTACT';
export const REMOVE_CONTACT = 'REMOVE_CONTACT';

export const SET_ACTIVE_FILTER = 'FILTER_BY_GROUP';
export const SEARCH_CONTACT = 'SEARCH_CONTACT';

export const ADD_GROUP = 'ADD_GROUP';

export const VALIDATE_FORM = 'VALIDATE_FORM';
export const SET_ADDING_MODE = 'SET_ADDING_MODE';
export const SET_EDITING_MODE = 'SET_EDITING_MODE';

export const ADD_FIELD = 'ADD_FIELD';
export const UPDATE_FIELD = 'UPDATE_FIELD';
export const RESET_FORM_FIELDS = 'RESET_FORM_FIELDS';

export const TOGGLE_MODAL_VIEW = 'TOGGLE_MODAL_VIEW';